### PR TITLE
Restrict negative numbers

### LINKED ISSUE #97: Disallow negative input of amount for Financial Entries

### PR DESCRIPTION
**Pull request by ctzeyong**
Exceptions are thrown when negative numbers are inputted
Fixes #97

### CODE REVIEW

**Review by Littleme1032 — COMMENTED** [review]
LGTM but just one question about what values to accept

**Review by limkongkiat — COMMENTED** [review]
Code looks good to me overall, I agree with Juven that we should disallow amount <= 0

**Comment by ctzeyong** [comment]
Just updated the rejection value to less than 0.01

**Review by limkongkiat — APPROVED** [review]
LGTM

**Pull request merged**
